version: '3.8'
services:
  spritecast-web:
    build: .
    ports:
      - "127.0.0.1:5001:5000"
    volumes:
      - .:/app
      - sprite-db:/app/instance
    environment:
      - FLASK_DEBUG=1

volumes:
  sprite-db: 
